- .env.clubhouse
- Dockerfile
- bin/run
- config/session.php
- docker/start-nginx
- docker/supervisord-nginx.ini
This allows the environment passed to the container to find its way to Laravel.
Fixes #9
> Cache Laravel configuration and routs when we start Nginx

- README.md
- app/Helpers/GlobalHelpers.php
- app/Http/Controllers/AuthController.php
- app/Http/Controllers/ConfigController.php
- app/Http/Controllers/PersonController.php
- app/Http/Controllers/PersonScheduleController.php
- app/Http/Controllers/SettingController.php
- app/Http/Controllers/TicketingController.php
- app/Http/Controllers/TimesheetController.php
- app/Lib/SMSService.php
- app/Lib/SalesforceClubhouseInterface.php
- app/Models/AccessDocument.php
- app/Models/AccessDocumentDelivery.php
- app/Models/LambasePhoto.php
- app/Models/ManualReviewGoogle.php
- app/Models/PersonYearInfo.php
- app/Models/Photo.php
- app/Models/Setting.php
- app/Policies/SettingPolicy.php
- app/Providers/AuthServiceProvider.php
- composer.json
- config/clubhouse.php
- database/migrations/2019_02_28_123922_create_settings_table.php
- database/seeds/DatabaseSeeder.php
- routes/api.php
- tests/Feature/ConfigControllerTest.php
- tests/Feature/PersonControllerTest.php
- tests/Feature/PersonScheduleControllerTest.php
- tests/TestCase.php
- Switched away from config('clubhouse.blah') to setting('blah') instead.
- Setting migration also includes setting definintions.
> Configuration stored in the database work. (called Setting)

- Dockerfile
- bin/.common.sh
- bin/build
- bin/test_docker
- bin/test_lint
- bin/test_unit
- bin/travis
- database/factories/RoleFactory.php
- docker/install_composer
- docker/install_php
> Run unit tests

- .travis.yml
- Dockerfile
- bin/.common.sh
- bin/build
- bin/travis
> Try to cache images again

- app/Lib/PotentialClubhouseAccountFromSalesforce.php
> Salesforce import: emergency contact is optional due to unannounced VolQ EC field removal.

- app/Http/Controllers/PersonController.php
- app/Models/Person.php
- database/migrations/2019_04_10_222214_add_callsign_normalized_to_person.php
- New column person.callsign_normalized - alphanumeric version of the callsign, no spaces or dashses present.
- New column person.callsign_soundex - php soundex version of the normalized callsign.
- Callsign search for search bar, Clubhouse messages, and Contact Ranger will search on normalized and soundex version. Sort order will have an extact match be the first item returned.
> Callsign search enhancements (hopefully!) for search bar/Contact Ranger/Clubhouse messages.

- Dockerfile
> Don't run composer as root

- bin/deploy
> Break up pipeline so errors are caught.

- bin/deploy
- bin/travis
https://github.com/burningmantech/ranger-deploy/pull/38
> More deploy changes

- app/Http/Controllers/MentorController.php
> uncomment status change for alpha conversion.. because like we're doing it for realz.

- app/Console/Commands/GroundhogDay.php
- app/Helpers/GlobalHelpers.php
- app/Http/Controllers/AccessDocumentController.php
- app/Http/Controllers/AssetController.php
- app/Http/Controllers/BulkUploadController.php
- app/Http/Controllers/ConfigController.php
- app/Http/Controllers/MentorController.php
- app/Http/Controllers/PersonScheduleController.php
- app/Http/Controllers/RbsController.php
- app/Http/Controllers/TicketingController.php
- app/Http/Controllers/TimesheetController.php
- app/Lib/Alpha.php
- app/Lib/BulkSignInOut.php
- app/Lib/RBS.php
- app/Models/AccessDocument.php
- app/Models/Asset.php
- app/Models/AssetPerson.php
- app/Models/ManualReview.php
- app/Models/Person.php
- app/Models/PersonEventInfo.php
- app/Models/Timesheet.php
- config/clubhouse.php
- tests/Feature/BmidControllerTest.php
- New command 'php artisan db:groundhog' to convert the current database into a groundhog day db.
- new global function current_year() to support a groundhog day environment. Uses the database time
if clubhouse.GroundhogDayServer configuration variable is true.
- most date('Y') calls have been replaced with current_year()
> More groundhog day server work.

- app/Console/Commands/GroundhogDay.php
- app/Http/Controllers/AccessDocumentController.php
- app/Http/Controllers/PersonScheduleController.php
- app/Http/Controllers/TicketingController.php
- app/Lib/WorkSummary.php
- app/Models/AccessDocumentDelivery.php
- app/Models/Bmid.php
- app/Models/Schedule.php
- app/Models/Timesheet.php
- Allow access_document_delivery to set method to mail and not have
a mailing address. Some ticket types the TRS will collect the address
not us.
- db:groundhog will bulid a separate database and dump that instead of
operating on the current database.
- fixed schedule/estimate so only counted hours are included.
- schedule & timesheet summaries correctly put non counted hours into other_duration.
> Ticketing work. db:groundhog command tweaks. more credit/hours fixups.

- app/Http/Controllers/RbsController.php
- app/Models/AccessDocument.php
- app/Models/Timesheet.php
- Do not fake out EU addresses. Only shipping to US addresses.
- Split out Reduced-Price tickets from everything else.
- Cleaned up SQL
> Reworked access doc retrieval for delivery based on 2019 policy.

- app/Http/Controllers/BulkUploadController.php
- app/Models/AccessDocument.php
- app/Models/Bmid.php
> Bug fix - update all WAPs when updating the access date thru Manage BMID or bulk uploader.

- app/Http/Controllers/AccessDocumentController.php
- app/Models/AccessDocument.php
- app/Models/Timesheet.php
- app/Policies/AccessDocumentPolicy.php
- routes/api.php
- Indicate if an access document is associated with a claimed Staff Credential. Used by the frontend to set delivery method for vehicle passes.
- New mark-submitted api endpoint to mark a list of claimed access documents as submitted.
- New method Timesheet::retrieveTopHourEarners to support a future DGS2 report.
> Ticketing work. Top hours earner method.

- app/Http/Controllers/RbsController.php
- app/Lib/Alpha.php
- app/Models/Bmid.php
- app/Models/Broadcast.php
- app/Models/PersonEventInfo.php
- app/Models/PersonMentor.php
- app/Models/Position.php
- app/Models/Timesheet.php
- app/Models/TraineeStatus.php
- app/Models/Training.php
- app/Models/TrainingSession.php
This should have been addressed earlier in the year and somehow dropped off the radar between 2018 and now.
Will need to find a better solution later to support multiple training positions for an ART.
> Hacked in HQ refresher training position into ART Training. ARGH.

- app/Lib/ShiftReporting.php
- app/Models/Position.php
- Extended Command view to include post-event period.
- Folded Gerlach Patrol - Green Dot into Gerlach Patrol column
- Added GP-GD to Green Dot view
- Added WESL to Command view
> Coverage Report tweaks.

- app/Models/PersonEventInfo.php
- app/Models/Training.php
> Fix HQ Training Refresher to show as passed training. Removed debugging statement.

- app/Http/Controllers/RbsController.php
- app/Lib/RBS.php
- app/Models/BroadcastMessage.php
- app/Policies/BroadcastPolicy.php
- Use laravel policies instead of role check.
- Estimated broadcast person count is now exact.
- Fixed review broadcast receipient delivery methods. (stopped numbers were incorrectly being included in review.)
> Various RBS tweaks & bug fixes.

- app/Helpers/GlobalHelpers.php
- app/Http/Controllers/ApiController.php
- app/Http/Controllers/AuthController.php
- app/Http/Controllers/ContactController.php
- app/Http/Controllers/PersonController.php
- app/Http/Controllers/PersonScheduleController.php
- app/Http/Controllers/SalesforceController.php
- app/Lib/RBS.php
- new global function mail_to which is a wrapper for Mail:to(..)->send(...) with exception handling, and logging.
- Report mail failure back to user when the reset password mail fails.
> Catch all mail exception, log the error, and recover gracefully.

- app/Console/Commands/TestMailCommand.php
- app/Mail/TestMail.php
- app/Models/BroadcastMessage.php
- app/Policies/BroadcastPolicy.php
- resources/views/emails/test-mail.php
- The unknown phones report was overly restrictive -- nobody was being allowed to run it.
- Added 'test:mail' command to send a simple test email out to an email specified on the command line.
> Fixed RBS permission bug. Added test mail command.

- app/Http/Controllers/PersonScheduleController.php
- app/Http/Controllers/TimesheetController.php
- app/Models/Person.php
- app/Models/Schedule.php
- app/Models/Training.php
- tests/Feature/PersonScheduleControllerTest.php
- Do not require taking the manual review
- Do not recommend working a Burn weekend shift
- Do not require dirt training.
> Non rangers policy changes.

- app/Models/Photo.php
> Hack fix - Allow Miss Piggy to see the upload url even tho photo uploading is disabled.

- app/Http/Controllers/TimesheetController.php
- app/Http/Controllers/TimesheetMissingController.php
- app/Models/Timesheet.php
- app/Policies/TimesheetPolicy.php
- tests/Feature/TimesheetControllerTest.php
- Mark timesheet entry & timesheet missing entry  as resubmitted for review when notes is updated.
- Audit log all timesheet entries - just. in. case.
- Tightened up timesheet policies.
> Timesheet corrections work.

- app/Http/Controllers/PersonScheduleController.php
- app/Models/Schedule.php
Reverts burningmantech/ranger-clubhouse-api#219
> Revert "Don't count hours for non credit earning shifts."

- app/Http/Controllers/TimesheetController.php
- app/Http/Controllers/TimesheetMissingController.php
- app/Models/Schedule.php
- app/Models/Timesheet.php
- database/migrations/2019_11_18_104922_add_slot_id_to_timesheet.php
- Added slot_id to to timesheet entries
- Try to associate shift sign up with timesheet entry when doing a bulk sign in
> Associate timesheet entries with shift sign up.

- Dockerfile
- bin/run
- docker/clubhouse-worker
> Add script to run background worker

- app/Models/PersonEventInfo.php
- app/Models/PersonPosition.php
- app/Models/Position.php
- app/Models/Slot.php
- app/Models/Timesheet.php
- All granted training positions are returned. Positions depending on said trainings will continue to be included.
- GD mentee shift and timesheet entry is returned if the person is determeined to be GD mentee.
> Restructed the Event Info API to be training centric.

- app/Http/Controllers/PersonScheduleController.php
- app/Models/Position.php
- app/Models/Setting.php
- app/Models/Slot.php
- database/migrations/2019_12_15_102855_add_fields_to_position.php
- database/seeds/SettingTableSeeder.php
- tests/Feature/PersonScheduleControllerTest.php
- TrainingFullEmail setting has been removed Superseded by position.slot_full_email
- Only enforce multiple enrollments IF position.prevent_multiple_enrollments is true.
> Added slot full email and prevent multiple enrollments field to position table.

- app/Http/Kernel.php
- composer.json
- composer.lock
- config/cors.php
- tests/Feature/TimesheetControllerTest.php
- Fixed timesheet update test. year was hardcoded.(d'oh!)
> Upgrade to Laravel 6.9 & friends.

- app/Http/Controllers/ApiController.php
- app/Http/Controllers/AuthController.php
- app/Http/Controllers/ConfigController.php
- app/Http/Controllers/PersonController.php
- app/Http/Controllers/PersonScheduleController.php
- app/Http/Filters/PersonFilter.php
- app/Models/Person.php
- app/Models/PersonPhoto.php
- app/Models/Schedule.php
- app/Models/Setting.php
- app/Models/Slot.php
- app/Models/TraineeStatus.php
- app/Policies/PersonPolicy.php
- composer.json
- config/app.php
- database/factories/PersonFactory.php
- database/migrations/2019_12_20_160318_add_milestones_to_person.php
- routes/api.php
- new last login & last seen fields
- new /person/{ID}/milestones endpoint to support onboarding checklists.
> Onboarding checklist work.

- app/Http/Controllers/MotdController.php
- app/Models/Motd.php
- app/Policies/MotdPolicy.php
- database/migrations/2020_02_09_165557_add_types_to_motd.php
- routes/api.php
- Addresses problem from last year when ticketing MOTDs were seen by PNVs & Alphas.
> Added for_{pnvs,auditors,rangers} columns to motd so announcement filtering can happen.

- app/Console/Commands/PhotoLambaseConvertCommand.php
- app/Http/Controllers/PersonPhotoController.php
- app/Models/PersonPhoto.php
- app/Models/Setting.php
- config/clubhouse.php
- config/filesystems.php
- database/migrations/2020_01_11_162151_clubhouse_photo.php
- Swapped PhotoStorage from a setting to a config variable since it's a deployment dependent thing.
- Remove PhotoStorage from settings table.
> Support for using staging/ as a photo directory when running a Staging server.

- Dockerfile
- app/Console/Commands/ClubhouseDailyReportCommand.php
- app/Console/Commands/ClubhousePhotoPendingCommand.php
- app/Console/Kernel.php
- app/Http/Controllers/MaintenanceController.php
- docker/clubhouse-worker
- docker/install_php
- docker/queue-worker.ini
- docker/schedule-worker
- routes/api.php
- Moved the daily report and photo pending emails into two new commands (clubhouse:daily-report & clubhouse:photo-pending) that are run through the Laravel Task Scheduling.
- Set the timezone on the Docker instances to be America/Phoenix aka UTC-07 without daylight savings obseravtion.
> Schedule and worker queues turned on!

- app/Http/Controllers/IntakeController.php
- app/Http/Controllers/SalesforceController.php
- app/Lib/Alpha.php
- app/Lib/Intake.php
- app/Lib/PotentialClubhouseAccountFromSalesforce.php
- app/Lib/SalesforceClubhouseInterface.php
- app/Models/PersonIntake.php
- app/Models/PersonStatus.php
- app/Models/Setting.php
- app/Models/TrainingSession.php
- database/migrations/2020_03_11_082010_add_personnel_to_notes.php
- routes/api.php
- tests/Feature/IntakeControllerTest.php
- Personnel team has notes & ranks like RRN, VC, and Mentors.
- Black flag has been removed in favor of Personnel rank 4.
- Salesforce import will pull the VC comments and place them into the intake VC notes.
- Salesforce import will update an existing account as long as the status is auditor or past prospective.
> Intake work - Personnel notes & Salesforce imports.

- app/Http/Controllers/PersonScheduleController.php
- app/Models/ApiModel.php
- app/Models/Position.php
- app/Models/Schedule.php
- app/Models/Slot.php
- composer.lock
- database/migrations/2020_03_19_161147_rename_slot_full_email.php
- tests/Feature/PersonScheduleControllerTest.php
- Sign up statuses turned into constants.
- Minor cleanup on sign up failure logging
- Renamed position.slot_full_email to contact_email
- All sign up forces require confirmation
> Sign up tweaks.

- .github/workflows/cicd.yml
- Dockerfile
- app/Http/Controllers/TimesheetController.php
- app/Models/Training.php
- app/Models/TrainingSession.php
- bin/build
- composer.lock
- Some minor documentation effort, and function argument typing.
> Indicate if the trainer group in a training session is a non-associate trainer position.

- app/Console/Commands/ClubhouseGroundHogDayCommand.php
- app/Console/Commands/ClubhouseRedactDatabaseCommand.php
- app/Http/Controllers/PersonController.php
- app/Lib/RedactDatabase.php
- app/Models/Person.php
- app/Models/Setting.php
- database/seeds/AdminPersonTableSeeder.php
- database/seeds/DatabaseSeeder.php
- database/seeds/EventDatesTableSeeder.php
- database/seeds/HelpTableSeeder.php
- database/seeds/PositionTableSeeder.php
- database/seeds/RoleTableSeeder.php
- database/seeds/SettingTableSeeder.php
- New command 'clubhouse:redact-db' to create redacted database
- Renamed command 'db:groundhogday' to 'clubhouse:groundhog-day'
- Added seeders for position, setting, role, event dates, and admin user
> Redaction, Ground Hog Day, and Seed database work.

- database/migrations/2020_05_19_153417_drop_mentor_columns.php
Superceded by the Unified Flagging View work.
> Removed person.{mentors_flag,mentors_flag_note,mentors_notes} columns.

- app/Http/Controllers/PersonController.php
- app/Http/Controllers/PersonMessageController.php
- app/Http/Controllers/PersonScheduleController.php
- app/Http/Controllers/SmsController.php
- app/Http/Controllers/TicketingController.php
- app/Http/Filters/PersonFilter.php
- app/Lib/Milestones.php
- app/Lib/RBS.php
- app/Models/AccessDocument.php
- app/Models/Bmid.php
- app/Models/EventDate.php
- app/Models/Motd.php
- app/Models/Person.php
- app/Models/PersonEventInfo.php
- app/Models/PersonPosition.php
- app/Models/Position.php
- app/Models/Schedule.php
- app/Models/Timesheet.php
- app/Models/TraineeStatus.php
- app/Models/Training.php
- database/factories/PersonFactory.php
- database/migrations/2020_08_16_101204_add_reviewed_pi_at_to_person.php
- routes/api.php
- tests/Feature/PersonScheduleControllerTest.php
- new column person.reviewed_pi_at to track when the person updated their personal info
- relocated milestone code from PersonController into lib/Milestones.php
- Burn Weekend is computed, no longer dependent on a setting.
- Relocated training information from PersonEventInfo to Training.
> Checkpoint commit for Ranger dashboard.

- app/Http/Controllers/AccessDocumentController.php
- app/Models/AccessDocument.php
- app/Models/EventDate.php
- app/Models/Schedule.php
- composer.lock
- tests/Feature/PersonScheduleControllerTest.php
Implements https://github.com/burningmantech/ranger-clubhouse-web/issues/309
> Functionality to retrieve all access documents, not just the current ones, for a person.

- app/Http/Controllers/PersonMessageController.php
- app/Http/Controllers/SlotController.php
- app/Models/Slot.php
- SlotController::people has the option to return the sign ups photos.
- Dropped unused query option in Slot::findForQuery()
> Rollcall enhancements

- app/Models/PersonPosition.php
- app/Models/Position.php
- app/Models/Training.php
- database/migrations/2020_09_17_143217_add_active_flag_to_position.php
- tests/Feature/PositionControllerTest.php
Adds the ability to mark a position either active or inactive. 
> ⚠️ Required by burningmantech/ranger-clubhouse-web#738
> Add an active status to Positions

- app/Http/Controllers/AccessDocumentController.php
- app/Lib/Milestones.php
- app/Models/EventDate.php
- app/Models/Schedule.php
- resources/views/emails/online-training-enrollment.blade.php
- Changed the After Event period to start on the Saturday after Labor Day at noon.
- Include estimated hours and credits based on sign ups in milestone data.
- Updated the LMS url in the account creation email
- Updated the access document controller to use constants instead of strings.
> More dashboard work.

- composer.json
- composer.lock
- tests/Feature/PersonScheduleControllerTest.php
Removed the static function mocks for PersonScheduleControllerTest.php, and each test no longer has to run in a separate process resulting in a 3x testing speed increase.
> Bump laravel framework version. Speed up for PersonScheduleControllerTest.php.

- app/Http/Controllers/ApiController.php
- app/Models/Person.php
- composer.json
- composer.lock
- Removed iseed, not PHP 8 compatible yet and only used to create seeders from existing databases.
- Using DB::select() to perform an UPDATE statement triggers a problem when using newer mysql clients and older servers. Using DB::table()->update() instead.
> Prep for PHP 8.

- app/Http/Controllers/AuthController.php
- app/Http/Controllers/PersonController.php
- app/Http/Controllers/SalesforceController.php
- app/Http/Controllers/TimesheetController.php
- app/Mail/ResetPassword.php
- app/Mail/WelcomeMail.php
- app/Models/Person.php
- app/Models/PositionCredit.php
- resources/views/emails/reset-password.blade.php
- resources/views/emails/welcome.blade.php
- tests/Feature/PersonControllerTest.php
- Renamed reset_token to temp_token.
- Reworked PNV welcome email to use temporary token as part of new PNV account setup flow.
> Reset password and PNV welcome email work.

- app/Http/Controllers/ConfigController.php
- app/Http/Filters/PersonFilter.php
- app/Models/Setting.php
- app/Policies/PersonMessagePolicy.php
- composer.lock
Only allow LMYR/LMOP access to the Emergency Contact info and Clubhouse Messages
if LoginManagementOnPlayEnabled is on.
> Login Management On Playa work.

- app/Console/Commands/ClubhouseMoodleCompletion.php
- app/Console/Kernel.php
- app/Http/Controllers/OnlineTrainingController.php
- app/Lib/Moodle.php
- app/Mail/OnlineTrainingEnrollmentMail.php
- app/Models/PersonOnlineTraining.php
- app/Models/Setting.php
- database/migrations/2021_01_28_153101_add_moodle_to_person_online_training.php
- resources/views/emails/online-training-enrollment.blade.php
- tests/Feature/PersonScheduleControllerTest.php
- New Moodle* settings (credentials, course ids, etc.)
- Minor editing on course enrollment email
- Swapped scheduled task docebo-completion for moodle-completion.
> Moodle support work.

- app/Http/Controllers/IntakeController.php
- app/Lib/Intake.php
- app/Models/PersonIntakeNote.php
- app/Providers/RouteServiceProvider.php
- routes/api.php
Only the note creator may update or delete the note.
> Added intake note edit capability and deletion.

- app/Http/Controllers/OnlineTrainingController.php
- app/Http/Controllers/PersonController.php
- app/Http/Filters/TimesheetFilter.php
- app/Lib/BulkSignInOut.php
- app/Lib/Milestones.php
- app/Lib/Reports/FreakingYearsReport.php
- app/Models/Timesheet.php
- database/migrations/2021_01_30_184959_add_person_status_to_timesheet.php
Address issue https://github.com/burningmantech/ranger-clubhouse-web/issues/458
> Non Ranger timesheet support.

- app/Http/Controllers/AuthController.php
- app/Mail/OnlineTrainingCompletedMail.php
- app/Mail/OnlineTrainingEnrollmentMail.php
- app/Mail/PhotoApprovedMail.php
- app/Mail/PhotoRejectedMail.php
- app/Mail/ResetPassword.php
- app/Mail/WelcomeMail.php
- Use request()->getSchemeAndHttpHost() to find out the current host.
> Try to avoid static Clubhouse urls embedded in emails (reset password, welcome message, etc.)

- app/Http/Controllers/TicketingController.php
- app/Lib/Reports/TimesheetWorkSummaryReport.php
- app/Models/Setting.php
- app/Models/Timesheet.php
- docker/start-nginx
- routes/api.php
- New settings for All-You-Can-Eat pass thresholds (event week & event period), Shower Pogs, and Shower Access.
- Added (missing) Carbon parameter type for Timesheet::findShiftWithinMinutes.
- Added event:cache command to instance start up script.
> New api ticketing/threshold (for appreciation thresholds).

- app/Console/Commands/ClubhouseDailyReportCommand.php
- app/Http/Controllers/MaintenanceController.php
- app/Mail/DailyReportMail.php
- app/Models/EventDate.php
- app/Models/Setting.php
- composer.lock
- resources/views/emails/daily-report.blade.php
- resources/views/html-email.blade.php
- Use const to define setting types.
- Updated daily report email.
> Added DashboardPeriod setting to be able to force the period.

- Dockerfile
- app/Models/Person.php
- composer.json
- composer.lock
- database/factories/PersonFactory.php
- database/migrations/2021_03_14_163610_remetaphone_numeric_callsigns.php
Examples: '3pio' will match threepio. 'two step' will match 2step.
> Improved searching for callsigns with numerics.

- app/Http/Controllers/SurveyController.php
- app/Lib/SurveyReports.php
- app/Models/Survey.php
- app/Models/SurveyAnswer.php
- app/Models/SurveyGroup.php
- app/Models/SurveyQuestion.php
- database/factories/SurveyGroupFactory.php
- database/factories/SurveyQuestionFactory.php
- database/migrations/2021_03_16_124400_add_subreport_to_survey_group.php
- database/seeds/SurveySeeder.php
- database/seeds/TrainerSurveySeeder.php
- php-inis/xdebug.ini
- tests/Feature/SurveyControllerTest.php
- tests/Feature/SurveyGroupControllerTest.php
- tests/Feature/SurveyQuestionControllerTest.php
- Dropped survey_question.code column
- Added survey_question.summarize_rating column to indicate ratings are to be collected into a single report.
- Moved survey reporting code from SurveyController to App/Lib/SurveyReports
- Survey Groups can be split out from main report into their own report with titles.
> Survey Work. Removed hardcoded questions.

- app/Lib/SalesforceConnector.php
- Switched from curl to Guzzlehttp
- Log all request exceptions, json decode failures, and error results
- Updated to v51.0 service URLs
> Salesforce connector cleanup.

- app/Models/PersonLanguage.php
- Has radio search was looking at all checked out assets, not radio assets.
- On the on duty check, limit to current year for on duty to help with SQL optimization.
- Search was including locked person statuses. Limit to only active statuses.
> Search languages fixes & tweaks.

- app/Lib/BMIDManagement.php
- app/Models/Bmid.php
- app/Models/Person.php
- app/Models/PersonRole.php
- BMID filter was not finding people with qualified provisions.
-
> Provisions work.

- Dockerfile
- app/Http/Controllers/AssetAttachmentController.php
- app/Http/Controllers/AssetController.php
- app/Http/Controllers/AssetPersonController.php
- app/Http/Controllers/BmidController.php
- app/Http/Controllers/PersonController.php
- app/Http/Controllers/PositionController.php
- app/Http/Controllers/RadioCheckoutReport.php
- app/Http/Controllers/TimesheetMissingController.php
- app/Http/Controllers/VehicleController.php
- app/Lib/BMIDManagement.php
- app/Lib/Reports/AlphaShirtsReport.php
- app/Lib/Reports/LanguagesSpokenOnSiteReport.php
- app/Lib/Reports/PeopleByLocationReport.php
- app/Lib/Reports/PeopleByPositionReport.php
- app/Lib/Reports/PeopleByRoleReport.php
- app/Lib/Reports/PeopleByStatusReport.php
- app/Lib/Reports/RecommendStatusChangeReport.php
- app/Lib/Reports/SandmanQualificationReport.php
- app/Lib/Reports/VehiclePaperworkReport.php
- app/Models/AssetPerson.php
- app/Models/Bmid.php
- app/Models/Person.php
- app/Models/PersonLanguage.php
- app/Models/Position.php
- tests/Feature/AccessDocumentControllerTest.php
Reports relocated are:
- Alphas Shirts
- Languages Spoken On Site
- People by Location
- People by Role
- People by Position
- People by Status
- Recommend Status Change
- Sandman Qualification
- Vehicle Paperwork
> Moved more reporting code from controllers & models into app/Libs/Reports. No new functionality.

- app/Http/Controllers/TimesheetController.php
- app/Models/Timesheet.php
- app/Policies/TimesheetPolicy.php
- routes/api.php
- Added include_photo query parameter to timesheet index to include the person's photo.
> New api timesheet/{timesheet}/resignin to re-signin (restart) an accidental shift sign off.

- app/Http/Controllers/PersonController.php
- app/Http/Controllers/PersonScheduleController.php
- app/Models/PositionCredit.php
- app/Models/Schedule.php
- composer.lock
- tests/Feature/PersonScheduleControllerTest.php
- person/X/schedule API payload reduced in size by pulling out position information into a separate collection.
- Allow credits earn, schedule summary, sign up permission to be included in payload if desired. This helps to eliminate 3 additional API calls when trying to setup the various scheduling pages on the front end.
> New schedule listing API format.

- app/Http/Controllers/TimesheetController.php
- app/Lib/Reports/RangerRetentionReport.php
- app/Models/Position.php
- app/Policies/TimesheetPolicy.php
- routes/api.php
- tests/Feature/TimesheetControllerTest.php
Implements feature request https://github.com/burningmantech/ranger-clubhouse-web/issues/288
> New Ranger Retention Report api.

- app/Http/Controllers/AuthController.php
- app/Http/Controllers/TimesheetController.php
- app/Lib/Reports/ShiftCoverageReport.php
- app/Models/Position.php
- app/Models/Timesheet.php
Removed ONE positions bypass training checks and from the shift coverage report.
> De-ONE-ifying the backend.

- app/Console/Commands/ClubhouseGroundHogDayCommand.php
- app/Lib/BulkUploader.php
- app/Lib/RBS.php
- app/Models/Person.php
- app/Models/TrainingSession.php
- Fixed Bulk Uploader to use normalized callsigns instead of literal callsigns.
- Add photo url for a trainee
- New '--no-redact' option for clubhouse:groundhog-day command
- Correctly mark groundhog day (GHD) accounts as on site.
- Some GHD settings were not being .. well, set.
- For GHD accounts, ensure motorpool and radio agreements are signed.
> Various random tweaks.

- app/Http/Controllers/AssetPersonController.php
- app/Http/Controllers/PersonController.php
- app/Http/Controllers/PersonScheduleController.php
- app/Lib/Reports/TimesheetWorkSummaryReport.php
- app/Lib/TicketsAndProvisionsProgress.php
- app/Models/ApiModel.php
- app/Models/AssetPerson.php
- app/Models/Schedule.php
- app/Policies/PersonPolicy.php
- php-inis/xdebug.ini
- routes/api.php
- Turned on auditing for asset_person
- New tickets and provision progress API
> HQ Window Interface api work.

- app/Console/Commands/ClubhouseDailyReportCommand.php
- app/Http/Controllers/ApiController.php
- app/Models/Person.php
- app/Models/Role.php
- app/Models/Setting.php
- database/migrations/2021_12_08_180207_add_trainer_seasonal_role.php
- resources/views/components/html-email.blade.php
- resources/views/emails/daily-report.blade.php
- Per TA request new role "Training Seasonal". Similar to the Login Mgmt On Playa where the role is explicitly enabled.
- Added Login Mgmt & Training Seasonal role to the daily report.
> New role - "Training Seasonal"

- app/Http/Controllers/OnlineTrainingController.php
- app/Http/Filters/PersonFilter.php
- app/Lib/Milestones.php
- app/Lib/Moodle.php
- app/Models/Person.php
- app/Models/Setting.php
- app/Policies/PersonPolicy.php
- database/migrations/2022_03_21_114028_add_lms_username_to_person.php
- resources/views/emails/online-training-enrollment.blade.php
- Moodle username is generated from the callsign, no longer using email.
- New person.lms_username to track moodle username.
- New setting OnlineTrainingFullCourseForVets to control if vets will take the full course. (for 2022, later years may have a half course)
- Language tweaks to online course enrollment mail.
> Moodle integration work.

- app/Helpers/GlobalHelpers.php
- app/Http/Controllers/BroadcastController.php
- app/Http/Controllers/Clubhouse1LogController.php
- app/Http/Controllers/ContactController.php
- app/Http/Controllers/HandleController.php
- app/Http/Controllers/MaintenanceController.php
- app/Http/Controllers/OnlineTrainingController.php
- app/Http/Controllers/PersonController.php
- app/Http/Controllers/PersonPhotoController.php
- app/Http/Controllers/RbsController.php
- app/Http/Controllers/SalesforceController.php
- app/Http/Controllers/SettingController.php
- app/Http/Controllers/SmsController.php
- app/Models/ActionLog.php
- tests/Feature/PersonScheduleControllerTest.php
- Ensure Action Log records have the real time and not GHD simulated time.
> More GHD work to lock down/prevent services in GHD mode.

- app/Models/Person.php
Some very old, defunct accounts (mid-to-late 2000s) have no addresses on file. Allow the Admin & VCS to adjust the record (i.e., release the callsign) without requiring an address to be entered.
> Allow Admins & VCs to bypass address validation on moldy accounts (deceased/dismissed/resigned/retired)

- app/Lib/Reports/OnDutyShiftLeadReport.php
- app/Lib/Reports/ShiftCoverageReport.php
- app/Lib/Reports/ShiftLeadReport.php
- app/Models/AccessDocument.php
- app/Models/Bmid.php
- app/Models/Position.php
- app/Models/Slot.php
- database/migrations/2022_04_28_173246_add_is_job_provision_to_access_document.php
- Pulled ONE references
- Only report on active positions for SL Report
> Added access_document.is_job_provision. Shift Lead Report tweaks.

- app/Lib/Reports/ShiftCoverageReport.php
- app/Lib/Reports/ShiftLeadReport.php
- app/Models/Position.php
- Ensure Shift Lead only reports on active positions for the current year.
- Added Operator - Smooth to the Coverage report.
> Shift Lead & Coverage report tweaks.

- app/Lib/BMIDManagement.php
- Give a full report (RAD id, type, status, access date) on the problematic WAP
- Fix WAP priority when scanning for shifts before access dates. Submitted first, then claimed, then everything else.
- Break out submitted versus claimed/qualified WAPs with access dates after the first shift sign up
> BMID Sanity Checker work

- app/Lib/Milestones.php
- app/Lib/Scheduling.php
- Build up the ticketing milestones for non-rangers
- Don't present nor require the online course to be completed.
> Non Ranger milestones tweaks

- app/Lib/Reports/OnDutyShiftLeadReport.php
- app/Lib/Reports/ShiftLeadReport.php
On going pandemic concerns. The worry is a person may have to bail during the event, and forget to remove their pending sign ups.
> Return person on site field for Shift Lead Report API (scheduled signups).

- app/Exceptions/ScheduleSignUpException.php
- app/Http/Middleware/RequestLogger.php
- app/Lib/Reports/ShiftLeadReport.php
- app/Models/PersonSlot.php
- app/Models/Schedule.php
- app/Models/Slot.php
- app/Models/Survey.php
- app/Models/Training.php
- app/Providers/AppServiceProvider.php
- database/factories/SlotFactory.php
- database/migrations/2022_09_20_235413_add_timezone_to_slot.php
- tests/Feature/SlotControllerTest.php
- New slot.timezone column to store the timezone. Default is America/Los_Angeles
- Don't use database server to calculate if the slot has started or ended.
> Slot timezone support.

- app/Lib/BulkLookup.php
For https://github.com/burningmantech/ranger-clubhouse-web/issues/1140
> BulkLookup: add vintage and total years to response

- app/Lib/BulkUploader.php
This does a few related changes in order to make the change work OK and not be too error-prone:
* Stops setting future expiry dates for gift tickets, as this appears to be a bug. AFAIK, gift tickets can't be banked.
* Requires dates to be input with at least 5 characters, to prevent an access date from being confused with a source or expiry year.
* Requires sourceYear and expiryYear to be sensible, i.e. YYYY format and sourceYear <= expiryYear.
* Enhances an error message to suggest a date format.
https://github.com/burningmantech/ranger-clubhouse-api/issues/414
> BulkUploader: support source year and expiry year for access docs

- app/Http/Controllers/AgreementsController.php
- app/Lib/Agreements.php
- app/Lib/Milestones.php
- app/Models/Document.php
- app/Models/Person.php
- app/Models/PersonEvent.php
- app/Models/PersonRole.php
- app/Models/Role.php
- app/Policies/VehiclePolicy.php
- database/migrations/2022_12_03_141101_add_nda_to_person_event.php
- tests/Feature/AuthControllerTest.php
- tests/TestCase.php
Implements https://github.com/burningmantech/ranger-clubhouse-web/issues/1472
> Require NDA signature for LM role grantees.

- app/Http/Controllers/ConfigController.php
- app/Http/Controllers/PersonEventController.php
- app/Http/Controllers/TicketingController.php
- app/Lib/Milestones.php
- app/Models/PersonEvent.php
- routes/api.php
- Moved ticketing/progress to person-event/progress.
- Added pii_{started,finished}_at person_event columns to support PII review.
- New config/dashboard-period api to obtain the dashboard period.
> PII Review support APIs

- app/Http/Controllers/TrainingController.php
- app/Lib/Reports/TrainingSlotCapacityReport.php
- Return counts using the status of the sign-ups at the time of training.
- Include passed count, not-passed count, and total unique number of trainers.
> Training Capacity Report enhancements

- app/Http/Controllers/HandleReservationController.php
- app/Models/HandleReservation.php
- app/Policies/HandleReservationPolicy.php
- app/Providers/AuthServiceProvider.php
- database/factories/HandleReservationFactory.php
- database/migrations/2022_12_30_171846_create_handle_reservation_table.php
- routes/api.php
This is for https://github.com/burningmantech/ranger-clubhouse-web/issues/667
The next pieces will mostly be in the frontend, where we'll be reading and writing these objects
> Add handle_reservation table, model, and controller

- Dockerfile
- bin/test_syntax
`conf.d` is not `httpd.d` and the former is breaking in new images.
> Update config path

- app/Http/Controllers/TimesheetController.php
- app/Lib/TimesheetManagement.php
- app/Models/Timesheet.php
- Moved some business logic into app/Lib/TimesheetManagement.
- Unconfirm final confirmation when creating a new entry via signin or signout.
> Start of TimesheetController cleanup.

- app/Http/Controllers/HandleController.php
- app/Models/HandleReservation.php
I verified this works as expected through the web page http://localhost:4200/vc/handle-checker
Admin interface and bulk uploader coming soon
https://github.com/burningmantech/ranger-clubhouse-web/issues/667
> HandleController: return active handle reservations

- app/Http/Controllers/RoleController.php
- app/Lib/Membership.php
- app/Models/Person.php
- app/Models/PersonRole.php
- app/Models/Role.php
- app/Policies/RolePolicy.php
- composer.json
- composer.lock
- routes/api.php
- tests/Feature/RoleOperationTest.php
- Return associated team & positions if requested for role index.
- Restrict team manager assignment to Admin role
- Added role cache inspection api.
> Role & Team work.

- app/Lib/Membership.php
- app/Models/ActionLog.php
- app/Models/PositionRole.php
- app/Models/TeamRole.php
- resources/views/emails/daily-report.blade.php
- Role Cache was not being flushed for any team or position grant/revokes.
- Provide the team and role titles for role/team association updates on the action log.
- Fixed the daily report to list the role ids in case the roles disappeared (will be an extremely rare event.)
> More roles stuff.

- .github/workflows/cicd.yml
- Dockerfile
- app/Http/Controllers/AccessDocumentController.php
- app/Http/Controllers/TicketingController.php
- app/Lib/Reports/ProvisionUnsubmitRecommendationReport.php
- app/Lib/Reports/TopHourEarnersReport.php
- app/Lib/Reports/UnclaimedTicketsWithSignupsReport.php
- app/Lib/TicketAndProvisionsPackage.php
- app/Lib/TicketingManagement.php
- app/Lib/TicketingStatistics.php
- app/Models/AccessDocument.php
- app/Models/Setting.php
- app/Policies/AccessDocumentPolicy.php
- bin/checkphpsyntax
- database/migrations/2023_01_13_001226_add_special_types_to_access_document.php
- routes/api.php
- Had to comment out checkphpsyntax github step because only php-8.1 is deployed via ubuntu-latest (as of 1-31-23). Php-8.2 syntax is being used which php-8.1 does not like.
> First cut of LSD & Gift Ticket support.

- app/Http/Controllers/PersonController.php
- app/Lib/Agreements.php
- app/Lib/Membership.php
- app/Lib/Milestones.php
- app/Lib/PositionSanityCheck/TeamMembershipCheck.php
- app/Lib/Reports/PeopleByTeamsReport.php
- app/Models/Person.php
- app/Models/PersonTeam.php
- app/Models/Team.php
- app/Models/TeamManager.php
- database/migrations/2023_02_01_010852_create_team_manager.php
- New table team_manager so a Team Manager does not actually have to be a member of said team.
- The LMOP/LMYR signed NDA requirement was not being triggered because only the explicit role assignments were checked and not the team / positions associated role.
- Backed out Admin requirement for nominating team managers.
> Clubhouse Team Manager change and bug fixes.

- app/Jobs/AlertWhenSignUpsEmptyJob.php
- app/Lib/PositionSanityCheck/TeamMembershipCheck.php
- app/Lib/PositionSanityCheck/TeamPositionsCheck.php
- app/Mail/AlertWhenSignUpsEmptyMail.php
- app/Models/Position.php
- app/Models/Schedule.php
- app/Models/Slot.php
- database/factories/PositionFactory.php
- database/migrations/2023_02_09_154311_change_teams_categories.php
- database/migrations/2023_02_09_173103_change_position_alerts.php
- resources/views/emails/alert-when-sign-ups-empty.blade.php
- tests/Feature/PositionSanityCheckControllerTest.php
- Use team_category option instead of individual team position flags. (clearer to understand)
- Added support for when a slot becomes empty.
> Position tweaks.

- app/Http/Controllers/SettingController.php
- app/Http/Middleware/RequestLogger.php
- app/Models/ApiModel.php
- app/Models/PositionCredit.php
- app/Models/Setting.php
- tests/TestCase.php
- Improved setting caching
- Reworked position credit caching from static class property to Laravel's cache array. Octane will keep the app hot and the cache array is flushed automatically after each request.
> Reworked setting retrieval. Prep for Octane.

- app/Http/Controllers/EventDatesController.php
- app/Http/Controllers/PersonPogController.php
- app/Http/Controllers/TicketingController.php
- app/Http/Controllers/TimesheetController.php
- app/Lib/TimesheetManagement.php
- app/Models/EventDate.php
- app/Models/PersonEventInfo.php
- app/Models/PersonPog.php
- app/Models/Role.php
- app/Models/Setting.php
- app/Models/Timesheet.php
- app/Models/TimesheetLog.php
- app/Policies/TimesheetPolicy.php
- database/migrations/2023_03_25_151941_add_issued_at_to_person_pog.php
- database/migrations/2023_03_25_173152_add_shift_force_roll.php
- routes/api.php
- Added new CAN_FORCE_SHIFT role to separate out timesheet administration from forcing a shift check in.
- Added event period to PersonEventInfo results
- Added issued_at column to person_pog table.
- New setting MealHalfPogEnabled
- New timesheet api to delete a short timesheet entry.
> HQ Interface support changes.

- app/Lib/PotentialClubhouseAccountFromSalesforce.php
- app/Lib/ReservedCallsigns.php
- Comment out Chef Juke's reserved callsign due to his re-application.
- Allow non-ranger status account to be updated.
> Last minute Salesforce tweaks.

- app/Http/Controllers/IntakeController.php
- app/Http/Filters/PersonFilter.php
- app/Lib/Intake.php
- app/Lib/Reports/PeopleByRoleReport.php
- app/Models/Person.php
- app/Models/PersonIntakeNote.php
- app/Models/Role.php
- database/migrations/2023_04_07_235540_add_employee_code_to_person.php
- database/migrations/2023_04_09_210435_add_new_roles.php
- tests/Feature/IntakeControllerTest.php
- New role: Regional Management, used to enforce write-only Unified Flagging access.
- New role: Vehicle Management, future role to be used in the vehicle registry interfaces
- New role: Payroll, access upcoming payroll functions.
> New roles, and Intake / Unified Flagging tweaks.

- app/Http/Controllers/SlotController.php
- app/Lib/Reports/ScheduleByCallsignReport.php
- app/Lib/Reports/ScheduleByPositionReport.php
- Fixed a bug with bulk slot copying not carrying forward the timezone.
- Added timezones and duration to the Schedule By {Callsign, Position} reports.
> Timezone work.

- app/Http/Controllers/MentorController.php
- app/Http/Controllers/PodController.php
- app/Http/Controllers/SlotController.php
- app/Lib/Alpha.php
- app/Models/AlphaMentorPod.php
- app/Models/PersonPod.php
- app/Models/Pod.php
- app/Models/Slot.php
- app/Models/Timesheet.php
- app/Policies/PodPolicy.php
- database/factories/HelpFactory.php
- database/factories/PersonPodFactory.php
- database/factories/PodFactory.php
- database/migrations/2023_05_26_103152_create_pods.php
- routes/api.php
- tests/Feature/PodControllerTest.php
- Initial cut of Mentor / Alpha pods.
- Lays the groundwork to support Dirt Ranger pod assignments for Cruise Direction.
> Attack of the Pod People!

- app/Lib/Reports/ShiftCoverageReport.php
Reduced the 2,000+ queries down to 5 to 10 depending on the report type.
> Sped up the Shift Coverage report by 30x.

- app/Console/Commands/ClubhouseMoodleCompletion.php
- app/Lib/TicketingManagement.php
- Sped up current tickets api by ~30%
- Don't double scan the moodle course completion if the half course and full course ids are the same.
> Performance tweaks.

- app/Http/Controllers/AccessDocumentController.php
- app/Http/Controllers/TicketingController.php
- app/Lib/BMIDManagement.php
- app/Lib/BulkUploader.php
- app/Lib/GrantPasses.php
- app/Lib/PersonAdvancedSearch.php
- app/Lib/Reports/ClaimedTicketsWithNoSignups.php
- app/Lib/Reports/ProvisionUnsubmitRecommendationReport.php
- app/Lib/TicketingManagement.php
- app/Lib/TicketingStatistics.php
- app/Lib/TicketsAndProvisionsProgress.php
- app/Models/AccessDocument.php
- app/Models/Setting.php
- app/Providers/AppServiceProvider.php
- database/migrations/2023_09_17_115650_replace_rpt_with_spt.php
- resources/views/emails/rangers-who-need-waps.blade.php
- tests/Feature/AccessDocumentControllerTest.php
- tests/Feature/BulkUploadControllerTest.php
Brings the naming inline with the rest of the org. Rangers only ever used RPT whereas all other departments used SPT.
> Renamed Reduced-Price Ticket (RPT) to Special Price Ticket (SPT).

- app/Http/Controllers/SlotController.php
- app/Models/Slot.php
- routes/api.php
- Use to sanity check if the given start & finished date-times are appropriate for the position. i.e., see if the dates are outside the scheduled sign-up ranges.
> New API endpoint slot/check-datetime

- database/migrations/2023_10_04_094903_convert_person_slot.php
- Set timestamp dates '0000-00-00 00:00:00' to slot.begins (years 2009 & 2010?)
-  Rename timestamp to created_at
> person_slot schema cleanup.

- app/Http/Controllers/PositionLineupController.php
- app/Http/Controllers/SlotController.php
- app/Models/PositionLineup.php
- app/Models/PositionLineupMember.php
- app/Models/Slot.php
- app/Policies/PositionLineupPolicy.php
- database/migrations/2023_11_01_121539_position_lineup.php
- routes/api.php
Links positions so related shift sign-ups can be shown together. Primary use case is the mentor/mentee shifts.
> New position lineup feature.

- app/Http/Controllers/AgreementsController.php
- app/Lib/Agreements.php
- app/Lib/Milestones.php
- app/Models/Document.php
- app/Models/Person.php
- tests/Feature/RoleOperationTest.php
Consolidated document tag definitions into Document.php.
> Don't show the Personal Vehicle document if not eligible.

- app/Console/Commands/ClubhouseRedactDatabaseCommand.php
- app/Http/Controllers/ConfigController.php
- app/Lib/GroundHogDay.php
- app/Lib/RedactDatabase.php
- app/Models/ActionLog.php
- app/Models/ApiModel.php
- app/Models/Setting.php
- resources/views/emails/photo-pending.blade.php
- Set DatabaseCreatedOn to when the database was redacted.
- have /api/config return DatabaseCreatedOn if the training server
- Clear out the check-in person on assert_person during GHD setup. -
> Groundhog day redaction tweaks.

- app/Http/Controllers/PersonController.php
- app/Lib/Alpha.php
- app/Models/PersonMentor.php
- app/Models/Training.php
Reduced 2K selects down to ~30.
> Alpha SQL optimizations

- app/Http/Controllers/PersonMessageController.php
- app/Lib/RBS.php
- app/Models/PersonMessage.php
- database/migrations/2024_03_26_173104_add_broadcast_id_to_person_message.php
- Track which broadcast the mail was generated from
- Track which message this is replying to. (for future threading support.)
- ensure database column limits are respected.
> Minor mail enhancements

- app/Http/Controllers/TimesheetController.php
- app/Http/Controllers/TimesheetMissingController.php
- app/Lib/TimesheetManagement.php
- app/Models/Schedule.php
- app/Models/Timesheet.php
- app/Models/TimesheetMissing.php
- TimesheetMissing can provide a check on the times versus schedule sign-ups.
- Timesheet times check extended to desired changes.
- Return the slot.url info upon shift start, or position change.
> Timesheet work

- app/Http/Controllers/SlotController.php
- app/Lib/LinkSlots.php
- app/Models/Position.php
- app/Models/Slot.php
- app/Policies/SlotPolicy.php
- database/migrations/2024_04_02_120357_add_parent_position_id_to_position.php
- routes/api.php
API links the slots with their multiplier slots.
parent_position_id is used help link the slots together.
> New api slot/link-slots & added position.parent_position_id column.

- app/Http/Controllers/TimesheetController.php
- app/Lib/BulkSignInOut.php
- app/Lib/CSV.php
- app/Lib/MarcatoExport.php
- app/Models/Position.php
- app/Models/Timesheet.php
- Bulk Sign-in-&-out: log the lines submitted, and the results
- Moved MarcatoExport::writeCSV() into it's own file: CSV.php
- Added a some relationship associations to Timesheet.
> Minor tweaks.

- app/Http/Controllers/AccessDocumentController.php
- app/Http/Controllers/TicketingController.php
- app/Lib/BulkUploader.php
- app/Lib/GrantPasses.php
- app/Lib/TicketingManagement.php
- app/Lib/TicketingStatistics.php
- app/Models/AccessDocument.php
- app/Models/AccessDocumentChanges.php
- app/Models/Setting.php
- app/Policies/AccessDocumentPolicy.php
- composer.json
- composer.lock
- database/migrations/2024_04_29_184345_change_access_document_type.php
- routes/api.php
- tests/Feature/AccessDocumentControllerTest.php
- tests/Feature/BulkUploadControllerTest.php
- New Vehicle Pass Special Price access document type.
- vehicle_pass now vehicle_pass_gift.
- Grant VPs awards a Gift VP for Staff Credentials,
- Removed most calls to AccessDocumentChanges::log() - now handled through AccessDocument callbacks.
- Removed access-document/statuses endpoint.
- New access-document/X/status endpoint does what /statuses did except on a single document. Multiple records may be effected depending on the type and status.
- New settings to indicate SP and SP VP costs.
> Restructured how Vehicle Passes are handled due to 2024 ticket policy  changes.

- app/Http/Controllers/AccessDocumentController.php
- app/Lib/MarcatoExport.php
- app/Lib/TicketAndProvisionsPackage.php
- Allow a VP to be claimed if no ticket has been claimed.
- Don't return VP Gift as a gift item.
> BMID export updates for 2024. Ticketing changes.

- app/Http/Controllers/ProvisionController.php
- app/Lib/BulkUploader.php
- app/Lib/ProvisionMaintenance.php
- app/Models/ApiModel.php
- app/Models/PersonMessage.php
- app/Models/Provision.php
- Do not autobank event radios
- Business logic pulled from ProvisionController and placed into ProvisionMaintenance.php -
> Provision changes.

- app/Console/Commands/ClubhouseRangersWhoNeedWAPsReportCommand.php
- app/Mail/RangersWhoNeedWorkAccessPassesMail.php
- app/Models/Setting.php
- resources/views/emails/rangers-who-need-waps.blade.php
> Swat some WAP references in emails and commands.

- app/Http/Controllers/PersonController.php
- app/Http/Controllers/PersonOnlineCourseController.php
- app/Http/Filters/PersonFilter.php
- app/Lib/BulkLookup.php
- app/Lib/Reports/RangerRetentionReport.php
- app/Lib/UserInfo.php
- app/Models/ApiModel.php
- app/Models/Person.php
- app/Models/Timesheet.php
- database/migrations/2024_10_13_110531_add_years_to_person.php
- tests/Feature/PersonControllerTest.php
- Stored within the person table.
- Years are recomputed when timesheet entries are created or updated.
> Cache work years to avoid somewhat expensive computation.

- app/Models/Person.php
E.g., right apostrophe -> single quote.
> Callsign assignment - Convert Microsoft special characters to regular characters.

- app/Http/Controllers/PersonScheduleController.php
- app/Http/Controllers/VehicleController.php
- app/Lib/Reports/VehiclePaperworkReport.php
- app/Models/PersonSlot.php
- app/Models/Position.php
- app/Models/Slot.php
- database/migrations/2024_12_29_133444_add_mvr_signup_potential_to_position.php
Primary use case is Intercept where the MVR dashboard prompt & vehicle dashboard will only be visible after the person signs up for a shift.
> Added MVR signup eligibility.

- app/Http/Controllers/PositionController.php
- app/Http/Controllers/RoleController.php
- app/Http/Controllers/TrainingSessionController.php
- app/Models/Position.php
- app/Models/Role.php
- app/Policies/RolePolicy.php
- app/Policies/TrainingSessionPolicy.php
- routes/api.php
- Moved the graduation function from the ART Trainer permission into ART Graduate.
- New API role/create-art-roles to create the ART permissions for a training position.
> ART permission work.

- app/Models/PersonPhoto.php
- app/Models/Timesheet.php
- app/Models/TrainingSession.php
- database/migrations/2025_02_28_163225_load_on_trainers_report_flag.php
- Set the position to appear on the trainer's report. (two years late on this. derp.)
- Use the cached person.years_as_ranger instead of computing the years.
- Batch look up the trainee photos.
> Some Trainer's Report modifications.

- app/Lib/Reports/TrainingUntrainedPeopleReport.php
- Replaced raw sql with query builder.
- Bug fix: don't consider trainers untrained when they taught a session.
> Rebuilt Untrained People report

- app/Http/Controllers/TeamController.php
- app/Lib/Reports/DirectoryReport.php
- app/Models/Person.php
- app/Models/Team.php
- database/migrations/2025_03_14_211343_add_description_to_team.php
- Added team.description column
- Return the management positions for members in a cadre
- Return the (new) team description
> More directory work

- app/Http/Controllers/PersonController.php
- app/Http/Controllers/TimesheetController.php
- app/Lib/Reports/TimesheetByCallsignReport.php
- app/Lib/Reports/TimesheetByPositionReport.php
- app/Models/PersonTeam.php
- app/Models/Team.php
- app/Policies/TimesheetPolicy.php
- database/migrations/2025_03_16_174138_drop_is_manager_from_person_team.php
- tests/Feature/TimesheetControllerTest.php
For non-Clubhouse admins, filter the positions based on what Cadre & Delegation the user belongs to along with any teams they are a CTM for.
> Timesheet By {Callsign, Position} limited reporting.

- app/Http/Controllers/AccessDocumentController.php
- app/Lib/Reports/EarlyArrivalReport.php
- app/Models/AccessDocument.php
- app/Models/AssetPerson.php
- app/Models/EventDate.php
- app/Models/Provision.php
- app/Policies/AccessDocumentPolicy.php
- routes/api.php
> New Early Arrival Report api.

- app/Http/Controllers/PodController.php
- app/Models/Pod.php
- app/Models/Slot.php
- app/Policies/PodPolicy.php
- php-inis/xdebug.ini
- routes/api.php
- New movePerson api to move a person between pods.
- Don't round up the shift times to the top of the hour.
> Pod Management enhancements

- app/Lib/MarcatoExport.php
Month was used instead of minute.
> Fixed BMID export string.

- app/Http/Controllers/SurveyController.php
- app/Models/Person.php
- app/Policies/SurveyPolicy.php
Only the Survey Management Training permissions were being checked and not checking the ART ones.
> Fixed ART survey management permissions.

- resources/views/emails/contact.blade.php
> add breaks in "Contact Ranger" email messages

- app/Lib/Reports/SpigotFlowReport.php
API changes to support both pre-2025 and 2025+ spigot report changes
> Spigot change

- app/Lib/Reports/SpigotFlowReport.php
Was creating the `pnvStatus` associative array immediately after raw query, which was causing most records with `person_id = NULL` to be lost as each new one would overwrite the last
> Hotfix for spigot-change

- app/Jobs/TrainerReminderJob.php
- app/Lib/TrainerReminder.php
- app/Mail/TrainerReminderMail.php
- app/Models/Person.php
- app/Models/Slot.php
- database/migrations/2025_05_09_175405_add_did_notify_to_slot.php
- resources/views/emails/trainer-reminder.blade.php
- routes/console.php
Between April and August, send a reminder email to the trainers and managing cadre if a training session has no training results entered.
> New Trainer Reminder job & email.

- app/Http/Controllers/SurveyController.php
- app/Lib/SurveyReports.php
- app/Models/Survey.php
- app/Models/SurveyAnswer.php
- app/Models/SurveyQuestion.php
- Minor cleanup on permissions.
- De-anonymized responses for those with one of the Survey Management permissions appropriate for the survey.
> Survey tweaks

- app/Http/Controllers/AwardController.php
- app/Lib/Reports/ServiceYearsReport.php
- app/Policies/AwardPolicy.php
- routes/api.php
implement a Service Years report based on Freaking Years report
> Feature service years

- app/Http/Controllers/AccessDocumentController.php
- app/Http/Controllers/TicketingController.php
- app/Lib/TicketingManagement.php
- app/Models/AccessDocument.php
- app/Models/Setting.php
- Added a 2nd mailing option: USPS Priority.
- New price settings for standard and priority mailings.
- Fixed the bug where setting the delivery method for either Gift tickets, or regular tickets was updating the other.
> 2025 ticketing work.

- app/Lib/RedactDatabase.php
- app/Lib/UserAuthentication.php
- app/Models/Person.php
- database/migrations/2025_06_09_100655_increase_password_field.php
- Passwords will be gradually upgraded to Argon2ID as people login.
> Start using Argon2ID encryption instead of SHA1.

- app/Http/Controllers/TrainingController.php
- app/Lib/Reports/TrainingNotesReport.php
- app/Models/TraineeStatus.php
- app/Policies/TrainingPolicy.php
- routes/api.php
- Returns all notes and ranks given for a given ART and year.
> New Training Notes api.

- app/Http/Controllers/CallsignsController.php
- app/Http/Controllers/PersonController.php
- app/Http/Controllers/PersonMessageController.php
- app/Http/Controllers/TeamController.php
- app/Lib/GroundHogDay.php
- app/Lib/Intake.php
- app/Lib/PersonSearch.php
- app/Lib/RBS.php
- app/Models/Person.php
- app/Models/PersonMessage.php
- app/Models/PersonTeam.php
- app/Policies/PersonMessagePolicy.php
- app/Policies/TeamPolicy.php
- database/migrations/2025_07_07_111642_add_message_from_person_id_to_person_message.php
- tests/Feature/PersonControllerTest.php
- Messages have to have a sender type (Person, RBS, Team, Other) and a message type (Normal, Contact, Mentor)
- CallsignsController has been updated to use PersonSearch which is more capable than  Person::searchCallsigns (function has been removed)
- Groundwork has been laid to support messages from teams in the future.
- Added attributes to help the UI display the time in a user-friendly format.
> Reworked Clubhouse Messages.

- app/Http/Filters/PersonFilter.php
- app/Models/Role.php
- database/migrations/2025_08_13_093637_add_edit_emergency_contact_role.php
This is intended to handle the Pre-Event week before EMOP is activated yet On Site Registration is happening.
> New permission - Edit Emergency Contact Year Round

- app/Lib/RedactDatabase.php
This should resolve a problem a current WESL trainee is facing
> don't change email addresses when redacting for inactive Rangers
