app/Http/Controllers/SmsController.php

When the number begins with '+' followed by ten digits and the first
phone number digit is not a '1', AND the user is in the US, assume
the number was encorrectly entered and insert a 1 between the +
and number.

Reformat a phone number when its assumed to be a US number.

---

Dockerfile

Add `--no-plugins --no-scripts` arguments, per https://getcomposer.org/doc/faqs/how-to-install-untrusted-packages-safely.md

Run composer with more safety

---

app/Console/Commands/GroundhogDay.php
app/Models/Person.php
app/Models/Photo.php
app/Models/TimesheetMissing.php
database/migrations/2019_06_24_220101_switch_soundex_to_metaphone.php

- Using metaphone instead of soundex to reduce false positives.
- Search on email only when '@' is in the query string
- GroundHog Day - turn off manual review requirement

Switch over to metaphone for searching. Photo url tweaks. GHD tweaks.

---

app/Http/Controllers/PositionCreditController.php
app/Http/Controllers/SlotController.php
app/Models/ApiModel.php
app/Models/PersonMessage.php

Adds a saveOrThrow method to ApiModel.  This is often cleaner than
if (!$model->save()) {
return $this->restError(...);
}
because it will appropriately break out of a transaction or helper.

Throw a validation exception on bulk copy failure

---

app/Models/Schedule.php
app/Models/Slot.php

Signups were being allowed where a full day could be signed up for, and then a half-day training session. The reverse was already blocked.

Bug fix for multiple enrollments.

---

app/Http/Controllers/PositionController.php
routes/api.php

Returns each position with a few attributes.  For all_rangers and
new_user_eligible positions, returns a list of people who should have
the position but don't (excluding deceased, dismissed, etc. people).
For granted positions returns a list of people with the position.
Separately returns a slim view of all people who are referenced by one
of these positions.  The onPlaya parameter will return only people who
are on site.

People by position API implementation

---

app/Lib/ShiftReporting.php
app/Models/Position.php

* Add perimeter and mentor categories
* Add ride-along type positions to the corresponding positions
* Merge HQ pre-event into main HQ list now that positions can be combined
* Add new positions here and there

Coverage report additions

---

app/Console/Commands/LambaseSyncPhotosCommand.php
app/Http/Controllers/BmidController.php
app/Models/LambasePhoto.php
app/Models/Person.php
app/Models/Photo.php

- New command 'lambase:syncphotos' used to rebuild photo status cache and download available mugshots.

Fixed PhotoStoreLocally setting to work with photo caching for on playa operations.

---

app/Http/Controllers/TimesheetController.php
app/Http/Filters/TimesheetFilter.php
app/Lib/LambaseBMID.php
app/Models/Timesheet.php

- Fixed timesheet correction report which was including all unverified entry.
- Use new is_incorrect flag on timesheet update to differentiate between simply updating
the verified flag versus marking (or remarking) an entry incorrect.

Timesheet Corrections work.

---

app/Http/Controllers/PersonController.php
app/Http/Controllers/PersonMessageController.php
app/Http/Controllers/TimesheetController.php
app/Models/PersonMessage.php
app/Models/PersonPosition.php
app/Models/Timesheet.php
tests/Feature/TimesheetControllerTest.php

- person/{person_id}/positions has new option 'include_mentee' to include the mentee positions. Mentees positions may disappear after the person has been trained. Also include the Alpha position if the person has an alpha timesheet entry.
- Combined correction and missing timesheet requests into one report.
- Allow a message to be marked as unread

Timesheet corrections fixes.

---

app/Http/Controllers/SlotController.php
app/Http/Controllers/TrainingController.php
app/Http/Controllers/TrainingSessionController.php
app/Lib/Alpha.php
app/Lib/RBS.php
app/Models/Bmid.php
app/Models/Person.php
app/Models/PersonEventInfo.php
app/Models/PersonPosition.php
app/Models/Position.php
app/Models/Slot.php
app/Models/TraineeStatus.php
app/Models/TrainerStatus.php
app/Models/Training.php
app/Models/TrainingSession.php
app/Policies/TrainingSessionPolicy.php
database/factories/TrainerStatus.php
database/migrations/2019_11_10_202334_create_trainer_status_table.php
routes/api.php
tests/Feature/PersonControllerTest.php
tests/Feature/PersonScheduleControllerTest.php
tests/Feature/SlotControllerTest.php
tests/Feature/TimesheetControllerTest.php
tests/Feature/TrainingControllerTest.php

- New table: trainer_status. Use to indicate if a trainer attended/taught a session.
- Use trainer_status to determine if a person can sign into a position, and indicate if a training session was 'passed' as a trainer.
- New report training/{id}/trainer-attendance - retrieves all trainers for a module in a given year and indicates the status of each session signed up for.

Trainer Attendance work.

---

app/Http/Controllers/PersonMessageController.php
app/Lib/RBS.php
app/Models/Person.php
app/Models/PersonMessage.php
app/Models/PersonPhoto.php
bin/checkphpsyntax

- Send back the reject message for photo status (only reject reasons were sent)
- Clubhouse Messages were not honoring the RBS sandbox settings
- Ensure Cubhouse Messages block sending to inappropriate statuses (deceased, uberbonked, etc). Frontend already does this (via callsign lookup)

Minor tweaks.

---

app/Http/Controllers/TimesheetController.php
app/Lib/RedactDatabase.php
app/Models/Setting.php
app/Models/Timesheet.php
database/seeds/SettingTableSeeder.php
php-inis/xdebug.ini
tests/Feature/TimesheetControllerTest.php

People are only allowed to submit corrections until mid-to-late fall and
does not spill over into the new year.

Removed TimesheetCorrectionYear setting.

---

app/Http/Controllers/MotdController.php
app/Http/Controllers/PersonController.php
app/Http/Controllers/TimesheetController.php
app/Http/Controllers/TimesheetMissingController.php
app/Http/Controllers/VehicleController.php
app/Http/Filters/PersonEventFilter.php
app/Http/Filters/PersonFilter.php
app/Lib/RedactDatabase.php
app/Models/ApiModel.php
app/Models/EventDate.php
app/Models/Motd.php
app/Models/PersonMotd.php
app/Models/Position.php
app/Models/Timesheet.php
app/Policies/MotdPolicy.php
app/Policies/PersonPolicy.php
app/Policies/VehiclePolicy.php
database/migrations/2020_07_24_155418_enhance_motd.php
database/migrations/2020_07_24_155438_create_person_motd_table.php
database/migrations/2020_07_29_134241_convert_ts_confirmation_to_person_event.php
routes/api.php
tests/Feature/TimesheetControllerTest.php

- Added subject, expires_at columns to motd
- Added person_motd to track who read a motd.
- Added query parameters to motd/{index,bullentin}
- person/milestones: check for cheetah cub signups for inactive extensions & retirees.
- person/milestones: return vehicle requests if person is allowed vehicle stickers
- relocated person/vehicle-paperwork to  vehicle/paperwork
- Only un-confirm a timesheet if the entry is for the current year.
- converted the last of person.timesheet_confirm* to person_event.timesheet_confirm*
- setup person_event.timesheet_confirm for 2019.

MOTD enhancements, Ranger dashboard prep work, timesheet fixups.

---

app/Console/Commands/ClubhouseDailyReportCommand.php
app/Helpers/GlobalHelpers.php
app/Helpers/SqlHelper.php
app/Http/Controllers/AccessDocumentController.php
app/Http/Controllers/ApiController.php
app/Http/Controllers/AssetController.php
app/Http/Controllers/AuthController.php
app/Http/Controllers/ConfigController.php
app/Http/Controllers/PersonController.php
app/Http/Controllers/PersonPhotoController.php
app/Http/Controllers/PersonScheduleController.php
app/Http/Controllers/SlotController.php
app/Http/Controllers/SmsController.php
app/Http/Controllers/TimesheetController.php
app/Lib/RBS.php
app/Models/ActionLog.php
app/Models/AssetPerson.php
app/Models/Broadcast.php
app/Models/Clubhouse1Log.php
app/Models/ErrorLog.php
app/Models/EventDate.php
app/Models/Person.php
app/Models/Position.php
app/Models/Schedule.php
app/Models/Slot.php
app/Models/Survey.php
app/Models/Timesheet.php
app/Models/Training.php
tests/Feature/TimesheetControllerTest.php

- Removed SqlHelper::now() and the "now()" SQL function. Using now() (Carbon) exclusively, now. (All part of the plan to find a better training server solution with Ground Hog Day support.)
- Adjusted Burn Weekend to end on Monday @ 00:00 (late Sunday night)
- PersonController::userInfo - return the shift the person is signed into and figure out if the person is signed in as a mentor, mentee or other.

Addressed {SqlHelper,SQL,Carbon}::now() usage. Minor tweaks.

---

app/Http/Controllers/ConfigController.php
app/Http/Controllers/PersonController.php
app/Http/Controllers/PersonScheduleController.php
app/Http/Filters/PersonEventFilter.php
app/Lib/Milestones.php
app/Lib/Scheduling.php
app/Models/Schedule.php
app/Models/Setting.php
tests/Feature/PersonScheduleControllerTest.php

- Permission to sign up is broken into two pieces - all sign ups (excluding dirt training), and dirt training sign ups.
- Removed RadioCheckoutFormUrl setting
- Added RadioCheckoutAgreementEnabled setting
- person_event.asset_authorized is write restricted to self and admin. Login management no longer has write permission.

Reworked sign up blockers.

---

app/Console/Commands/ClubhouseGroundHogDayCommand.php
app/Console/Commands/ClubhousePurgeSettings.php
app/Http/Controllers/ApiController.php
app/Http/Controllers/AuthController.php
app/Http/Controllers/ConfigController.php
app/Providers/AppServiceProvider.php
docker/start-nginx

- New 'clubhouse:purge-settings' command to delete obsoleted settings from the database.
Run as part of the Docker image startup sequence.
- RANGER_CLUBHOUSE_GROUNDHOG_DAY_SERVER is treated as a datetime string instead of a boolean.
- Using Carbon::setTestNow() to time travel - JWT token generation requires special casing since
the embedded expiry timestamps have to be in the current timeline and not the simulated one.

New Clubhouse settings purge command. Groundhog Day work.

---

app/Http/Controllers/PositionController.php
app/Http/Controllers/TimesheetController.php
app/Lib/ShiftReporting.php
app/Models/Timesheet.php
tests/Feature/TimesheetControllerTest.php

> ⚠️ This PR is required by burningmantech/ranger-clubhouse-web/pull/752
Add the position active status to report endpoints so that the reports can display the status of positions.

Add positoin active status to report endpoints

---

app/Http/Controllers/PersonScheduleController.php
app/Models/ActionLog.php
app/Models/PersonSlot.php
app/Models/Schedule.php
routes/api.php
tests/Feature/PersonScheduleControllerTest.php
tests/TestCase.php

- Tests are set to the time {current year}-01-01 12:45:56 to help with scheduling testing.
- PersonSlot::deleteForSlot logs all sign ups before deleting the slot.

New API - person/N/schedule/log - retrieve the scheduling log for a person & year.

---

app/Http/Controllers/AuthController.php
app/Http/Controllers/PersonController.php
app/Mail/ResetPassword.php
app/Models/Person.php
resources/views/emails/reset-password.blade.php
tests/Feature/AuthControllerTest.php
tests/Feature/PersonControllerTest.php

- Temporary password (person.tpassword) has been redefined as a reset password token.
- /auth/login accepts a reset password token in addition to a email & password.
- Do not generate a new reset password token if the current token has not expired. Prevents multiple emails being sent out with different codes and confusing the user on which email is the right one.
- Reset password email revamped to send a reset password link, styled as a button, instead of the temporary password. No more copy-n-pasting.
- /person/X/password updated to accept a reset password token in place of the old password.

Changed reset password request flow.

---

app/Models/Person.php

- Remove Person::passwordMatch because there's no longer a second password to check (tpassword is a token, not an actual password to check against)

Frankenstein kant du da mathz. (token expiry check for generation was wrong.)

---

app/Http/Controllers/PersonController.php
app/Http/Filters/PersonFilter.php
app/Models/Person.php
app/Models/Role.php
app/Models/Setting.php
database/migrations/2020_12_29_122848_add_lm_on_playa_to_roles.php
tests/Feature/PersonControllerTest.php
tests/Feature/TimesheetControllerTest.php

- New role Login Management On Playa. Works exactly like Login Management except is controlled through the LoginManagementOnPlayaEnabled setting.
- New role Tech Ninja. Can only be granted/revoked by other Tech Nina roles. Groundwork for future features.
- Removed obsoleted de/serialization of Person->roles. The frontend uses a separate interface to query & update roles.

New roles - Login Management On Playa & Tech Ninja.

---

app/Lib/Moodle.php
app/Models/Setting.php

- Killed client id & password setting. Only need to use a web services token already setup in the app.
- Fixed minor bug with setting() - wasn't check on the empty values correctly for a settings array.
- Removed hardcoded web services name (d'oh!)

Moodle integration work.

---

app/Http/Controllers/ConfigController.php
app/Http/Controllers/PersonController.php
app/Lib/Milestones.php
app/Models/Bmid.php
app/Models/PersonEventInfo.php
app/Models/Setting.php
app/Models/Timesheet.php
app/Models/Training.php
database/factories/PersonOnlineTrainingFactory.php
tests/Feature/TimesheetControllerTest.php

- New settings OnlineTrainingOnlyForBinaries & OnlineTrainingOnlyForVets to control if either group only needs to complete Online Training to be consider "trained" for the event. (2021 event)
- person/X/event-info includes is_binary and online_training_only info
- Don't allow auditor registration if AuditorRegistrationDisabled is true

Online Training Only requirement work. Auditor registration disabled.

---

app/Lib/Reports/ShiftLeadReport.php
app/Models/Training.php

- Incorrect argument type was passed to Training::didPersonPassForYear().
- Added coded to work around differences in regular expressions between Mysql 5.0 ("spencer" style) and 8.0 (modern regexp)

Fixed shift lead report.

---

app/Http/Controllers/SlotController.php
app/Lib/Reports/ScheduleByPositionReport.php
routes/api.php
tests/Feature/PersonControllerTest.php
tests/Feature/SlotControllerTest.php

- Reduced payload by 10% by only returning the person id and not callsign for every single slot. Person info is returned in a separate key 'people'.
- Include email address if user has the privs.

Schedule By Position report changes. Switch bulk lookup from get to post for larger lookups.

---

app/Lib/RedactDatabase.php
app/Lib/Reports/ShiftCoverageReport.php
app/Lib/Reports/ShiftLeadReport.php

- Removed O.N.E. OOD position from Shift Coverage report.
- Only report on active positions if the current year is selected on the Shift Lead report.
- Don't reset the passwords when creating a redacted database.

Report fixes.

---

app/Lib/Reports/ShiftLeadReport.php
app/Models/Person.php
app/Models/Training.php

- API response payload has been reduced by 40%. Positions & slots columns are no longer inlined with each callsign row. Instead both are returned in their own response and each callsign row only references a slot and/or position id.
- Bulk look up passing Green Dot ARTs instead of individually looking up each person.
- Switch to using Person::summarizeGender() to count how many female GDs are scheduled, reduced down to one select statement, and eliminated use of the SQL REGEXP operator.

Shift Lead report performance work.

---

app/Http/Controllers/AlertController.php
app/Http/Controllers/ConfigController.php
app/Http/Controllers/PositionController.php
app/Http/Controllers/TimesheetController.php
app/Models/Position.php
app/Models/Schedule.php
app/Models/Setting.php
app/Models/Timesheet.php
app/Policies/AlertPolicy.php
app/Policies/PositionPolicy.php
tests/Feature/PositionControllerTest.php

- Position, RBS Alerts, and Role modifications require the Tech Ninja role.
- Bypass training checks for O.N.E positions
- New HQWindowInterfaceEnabled setting (for web client, no effect on backend operations.)
- Force all timesheet ONE position entries to be marked as  non-ranger volunteer to avoid inclusion in service years and other related things.

O.N.E. support changes. Start to use the Tech Ninja role for things.

---

app/Http/Controllers/PersonScheduleController.php
app/Http/Controllers/TimesheetController.php
app/Http/Controllers/TimesheetMissingController.php
app/Lib/BulkSignInOut.php
app/Lib/Milestones.php
app/Models/Schedule.php
composer.lock
tests/Feature/PersonScheduleControllerTest.php

- Don't return person/X/schedule as a REST like resource since it's no longer treated as a pseudo-table on the front end.
- Renamed Schedule::findSlotSignUpByPositionTime to findSlotIdsSignUpByPositionTime
- Fixed a bug associating a shift sign in with a slot sign up.
- Warn if an about-to-start shift is not within 15 minutes of the current time. Used by the HQ Window Interface to assist workers in telling Rangers to go chill for a bit more before working.
- Added and/or updated existing phpdoc comments.
- Fixed a bug where a cheetah cub shift was not reported correctly to the dashboard.

Scheduling work.

---

app/Console/Commands/ClubhouseGroundHogDayCommand.php
app/Http/Controllers/PersonController.php
app/Http/Controllers/PersonScheduleController.php
app/Http/Controllers/SmsController.php
app/Lib/RedactDatabase.php
app/Models/Bmid.php
app/Models/Schedule.php

- Save person-slot-{add,remove} events in the action log when creating a redacted database so the schedule log works.
- Don't mark a callsign search result as matching the fka if the query matches the beginnning of the callsign. Helps to reduce noise on the search bar with truncated callsigns (e.g. doctor hubcap -> hubcap).
- Fixed schedule credit estimates. All possible shifts were being scanned and not just the signed up shifts.
- Fixed BMID meals reporting

Various bug fixes.

---

app/Lib/ReservedCallsigns.php

Spelling: s/Exodous/Exodus/

---

app/Lib/BMIDManagement.php
app/Lib/GrantPasses.php
app/Models/AccessDocument.php

- Scan ALL access documents when trying to determine if a person's shift starts before an access document. Claim or Submitted WAP / SC takes precedences
- Include a reason why the checker was triggered
- Exclude auditors and past prospectives.

BMID Sanity Checker fixes.

---

app/Lib/TicketsAndProvisionsProgress.php
app/Models/AccessDocument.php
app/Models/Bmid.php
app/Models/PersonEventInfo.php

- Fixed shower pog & provision earning progression.
- do not automatically bank qualified provisions when an allocated one exists
- Indicate when the event radio(s) has been banked on the person event api.

Provision work.

---

app/Console/Commands/ClubhouseGroundHogDayCommand.php
app/Lib/MarcatoExport.php
app/Lib/TicketingStatistics.php
app/Models/AccessDocument.php
app/Models/Bmid.php
app/Models/Setting.php

- Fixed submitted count on ticketing stats api.
- Consume all meal allocations if meals are explicitly set or have any meal allocations (not grants)
- Shower export comment was include all possible sources (qualified, allocated, set), only the first one.
- WAP source was only using the first submitted or claimed doc, and not finding the most appropriate one. (i.e. SC + separate WAP with a date earlier than the SC).

Ticketing fixes, Marcato Exports tweaks, and other stuff.

---

app/Listeners/MailSentListener.php

My eyes are always triggered when I see potential catastrophic backtracking situations (e.g. having multiple ".*" in one regex which can overlap), hence I add the "not @" requirement to limit that.
Also this stops "thisisntburningman.com" from erroneously matching, and it allows for plural "rangers" as a prefix, as we have for the tech team (and maybe any other groups?)
Example and a few unit tests here: https://regex101.com/r/SPJtyu/2

MailSentListener: enhance the email regex a bit

---

app/Http/Controllers/TimesheetController.php
app/Lib/RedactDatabase.php
app/Lib/Reports/RadioEligibilityReport.php
php-inis/xdebug.ini
tests/Feature/TimesheetControllerTest.php

- Report on the last 3 events as per policy, not just the last 2.
- Return the years being reported on.
- Indicate what Shift Lead positions are being considered.

Radio Eligibility Report API adjustments

---

.github/workflows/cicd.yml

See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Replaced github action set-output deprecated function.

---

database/factories/PersonFactory.php

I'm pretty sure this fixes the flakiness we've been seeing in TimesheetControllerTest and AccessDocumentControllerTest. I suspect that we're creating Persons with duplicate callsigns, violating the constraint on the Person table. This change makes the tests totally reliable on my desktop (while I can easily reproduce the flakiness without the change), and without downsides, this seems worth merging.

PersonFactory: combine two words to make test callsigns

---

app/Http/Controllers/ProvisionController.php
app/Policies/ProvisionPolicy.php
tests/Feature/ProvisionControllerTest.php

- Look at Event Radios with status available and see if the person worked or checked out a radio. Mark as used if so.
- The type column was being used instead of status. (major d'oh!)
- Mark an allocated provision as used if the person had a submitted BMID.

Fixed provisions clean up.

---

app/Http/Controllers/ApiController.php
app/Http/Controllers/PersonController.php
app/Http/Controllers/PersonScheduleController.php
app/Models/Person.php
tests/Feature/PersonScheduleControllerTest.php

- Starting with the 2022 event, the T.A. has requested the Training role only be assigned to T.A. cadre members. All other eligible trainers will be given the Training Season role. This allows the Admin role to be deprecated in favor of the Training role for performing privileged Training interface actions (e.g., sign up trainees).
- The "true" (unadjusted/un-massaged) roles are being tracked. A new method, `$user->hasTrueRole()` checks for the unadjusted role grants. (e.g., we want to identify the explicitly granted Training role, and not the Training Seasonal role which masquerades as the Training role. hasRole(TRAINER) will be true, where as hasTrueRole(TRAINER) will be false.)

Per TA & council manager request, allow Training role to sign up trainees.

---

app/Models/HandleReservation.php

reason should be nullable, since that's how we made it in the schema
(and the field ought to be optional). end_date also should be nullable,
and that took an extra step of defining an Attribute which converts
empty values to null.
https://github.com/burningmantech/ranger-clubhouse-web/issues/667

HandleReservation: allow for empty end_date and reason

---

app/Http/Controllers/EmailHistoryController.php
app/Http/Controllers/PersonController.php
app/Lib/PersonSearch.php
app/Models/EmailHistory.php
app/Models/Person.php
app/Policies/EmailHistoryPolicy.php
app/Policies/PersonPolicy.php
app/Providers/AuthServiceProvider.php
database/migrations/2023_01_20_165433_create_email_history.php
routes/api.php

- New table email_history to track updates to an account's email address.
- New person/search api to replace the existing person/index api. New api breaks out the search results into different categories instead of mushing everything together. The changes are partly to support email history tracking and being able to search on up old email addresses in the search bar.

New Email address (change) history tracking. New person fuzzy search API.

---

app/Http/Controllers/PositionController.php
app/Http/Controllers/RoleController.php
app/Http/Controllers/SettingController.php
app/Http/Controllers/TeamController.php
app/Lib/ClubhouseCache.php
app/Models/Person.php
app/Models/PersonPosition.php
app/Models/PersonRole.php
app/Models/PositionRole.php
app/Models/Setting.php
app/Models/TeamRole.php
config/cache.php
tests/Feature/RoleOperationTest.php

The laravel scheduler wants a persistent external cache like a database or Redis to prevent duplicate task executions. There appears not to be a way to configure the scheduler to use a different cache store other than the default. Because of this, the Clubhouse has use an explicitly defined store (Octane -- a super fast in-app ephemeral cache). The default cache cannot be set to Octane. Sigh.

Factored out cache operations into ClubhouseCache.

---

app/Helpers/GlobalHelpers.php
app/Http/Controllers/AssetController.php
app/Http/Controllers/ProvisionController.php
app/Http/Controllers/RadioCheckoutReport.php
app/Models/Asset.php
app/Models/AssetPerson.php
database/migrations/2023_02_26_173705_add_people_to_asset_person.php
database/migrations/2023_02_27_095240_add_consumed_year_to_provision.php

- New column provision.consumed_year to track what year the provision was used.
- New columns asset_person.check_{in,out}_person_id to track who handed out and received the asset.
- Fixed the eligibility indicator on the radio check out report. (was using the only radio_eligibly table, not the new provision one)

Track who actually checked in & out an asset.

---

app/Http/Controllers/OnlineTrainingController.php
app/Jobs/OnlineTrainingSyncPersonJob.php
app/Lib/Moodle.php
app/Mail/ClubhouseMailable.php
app/Mail/OnlineTrainingResetPasswordMail.php
app/Models/Person.php
app/Policies/PersonOnlineTrainingPolicy.php
resources/views/emails/online-training-password-reset.blade.php
routes/api.php

- New API so the O.C. password can be reset from the Clubhouse dashboard.
- Email the user when said password is reset.
- Sync the user's info when enrolling in a course, or when the user's callsign, first name, last name, or email address changes.

Online Course enhancements.

---

app/Http/Controllers/TicketingController.php
app/Lib/TicketsAndProvisionsProgress.php
app/Models/Schedule.php
app/Models/Setting.php

- Per Council request, Shower Access qualification is now based off Event Week hours (60 hours), or Pre-/Event/Post- hours (130 hours).
- Split ShowerAccessThreshold setting into ShowerAccessEventWeekThreshold, and ShowerAccessEntireEventThreshold.

Handle new shower access qualification for 130 hour pre-/event/post-.

---

app/Http/Controllers/PersonScheduleController.php
app/Models/Schedule.php
routes/api.php

- Include all future shifts, not just the imminent ones, and return the time parameters used to determine imminent and early starting shifts.

Rename schedule imminent endpoint to upcoming.

---

app/Http/Controllers/HandleController.php
app/Http/Controllers/SalesforceController.php
app/Lib/PotentialClubhouseAccountFromSalesforce.php
app/Lib/SalesforceClubhouseInterface.php
app/Models/Person.php

- Allow retired & resigned account non-vintage handles to be recycled for new applicants.
- Use normalize callsign lookup instead of raw comparison.

Salesforce import work.

---

app/Lib/Reports/SpecialTeamsWorkReport.php

- Deceased, dismissed, uberbonked, and suspended are filtered out.

Have the People By Special Teams report filter out problematic statuses.

---

app/Http/Controllers/PersonScheduleController.php
app/Http/Controllers/SlotController.php
app/Lib/BMIDManagement.php
app/Lib/Milestones.php
app/Lib/Reports/ScheduleByCallsignReport.php
app/Lib/Scheduling.php
app/Models/ApiModel.php
app/Models/PositionCredit.php
app/Models/Schedule.php
app/Models/Slot.php
app/Models/TrainerStatus.php
app/Models/Training.php
app/Providers/AppServiceProvider.php
composer.json
composer.lock
database/factories/SlotFactory.php
database/migrations/2023_05_03_223354_add_start_year_to_position_credit.php
database/migrations/2023_05_04_123634_add_timezone_abbr_to_slot.php
database/migrations/2023_05_04_155212_add_virutal_columns_to_slot.php
php-inis/xdebug.ini
resources/views/emails/welcome.blade.php

- Boosted scheduling retrieval performance by 50% to 70%.
- New slot columns: begins_year, begins_time, ends_time, timezone_abbr to aid slot retrieval performance.
- Switched app/Models/Schedule from a pseudo ApiModel to a pure php class. (faster serialization)
- Bulk compute slot credits instead of using magic methods and hitting the position credit cache over & over.
- Return the burn weekend recommendation when removing a slot sign up. (trying to reduce the number of API calls on the frontend.)
- Use the new slot.begins_year column for faster queries instead of year(slot.begins)
- Added virtual columns start_year & end_year to position_credit for faster queries.
- Refactored full day training detection (more api call reduction.)
- Added clockwork package to aid development.

Scheduling performance work.

---

app/Http/Controllers/PersonScheduleController.php
app/Models/Schedule.php
app/Models/Slot.php
tests/Feature/SlotControllerTest.php

- Schedule summary broke due to the performance tweaks done in a previous commit
- Prevent the trainer_slot_id from being set to itself, and an ensure the trainer slot does not point back to the current slot.

Slot fixes.

---

app/Lib/Milestones.php
app/Models/Position.php
app/Models/Role.php
app/Models/Setting.php
app/Policies/TimesheetPolicy.php
database/migrations/2023_07_24_163001_add_timecard_year_round_to_role.php

- Allows users to self clock in/out without requiring LMYR/LMOP. Intended for NVO / DPW Rangers who are working earlier in the summer.

New Timecard Year Round permission.

---

app/Http/Controllers/TimesheetMissingController.php
app/Models/TimesheetMissing.php

- Don't throw an exception if the person does not hold the position. Return as a REST error.
- Initialize the new timesheet variable (new_{off_duty,new_on_duty,position_id}) to null.

Missing timesheet tweaks

---

app/Lib/PositionSanityCheck.php
app/Lib/PositionSanityCheck/DeactivatedAccounts.php
app/Lib/PositionSanityCheck/RetiredAccounts.php
app/Models/Person.php
app/Models/PersonPosition.php

- Ensure retired accounts only have the new user eligible flagged positions (similar to a prospective or auditor)
- Revoke all positions for deactivated accounts (bonked/uberbonked, dismissed, resigned, past prospective)

New Position Sanity Checker functionality.

---

app/Lib/PositionSanityCheck/ShinnyPenniesCheck.php
app/Lib/Reports/TimesheetSanityCheckReport.php
tests/Feature/PositionSanityCheckControllerTest.php
tests/Feature/TimesheetControllerTest.php

- Use active status and alpha timesheet entry to scan for dirt - shiny penny issues.
- Slot duration was not being returned for the possibly too long timesheet entries.

Timesheet and Position sanity checker fixes.

---

app/Http/Controllers/AssetController.php
app/Http/Controllers/RadioCheckoutReport.php
app/Models/Asset.php
app/Models/AssetPerson.php
database/migrations/2023_09_23_190121_asset_cleanup.php

- Column renaming: create_date -> created_at, description -> type, temp_id -> description
- Added new column year to indicate event year.
- New enum type 'temp-id' to indicate temporary BMID.
- drop old vehicle columns - model, subtype, color, style.
- Fixed up invalidate creation dates

Asset schema cleanup and added new Temporary ID asset type.

---

app/Console/Commands/AccountSnatchCommand.php
app/Console/Commands/GrantAllRolesCommand.php

- clubhouse:grant-all-roles to help bootstrap a new developer by granting all the roles to an account.
- clubhouse:account-snatch to set an account password to abcdef. Useful to debug an account locally.
Both commands cannot be run in production.

New Developer commands.

---

app/Lib/PositionSanityCheck/DeactivatedAccounts.php
app/Lib/PositionSanityCheck/DeactivatedPositionCheck.php
app/Lib/PositionSanityCheck/DeactivatedTeamsCheck.php
app/Lib/PositionSanityCheck/TeamMembershipCheck.php
app/Lib/PositionSanityCheck/TeamPositionsCheck.php
app/Models/Person.php

- Added team membership check & removal for deactivated accounts
- Ignore all other PSC checks for deactivated accounts.

Position Sanity Checker changes.

---

app/Lib/Milestones.php
app/Models/Timesheet.php

Any Shiny Pennies with a single Alpha shift and no other work will not be reported as needing their timesheet confirmed.

Fixed reporting on unverified timesheets.

---

app/Lib/TimesheetManagement.php
app/Models/Position.php
app/Models/Training.php

- Report back the Sandman disqualification year cut off.
- Consider all positions as requiring an In-Person Training except those with the no_training_required flag set.

Tidied up the unqualified sign in position reporting.

---

app/Attributes/BlankIfEmptyAttribute.php
app/Attributes/NullIfEmptyAttribute.php
app/Http/Controllers/TimesheetController.php
app/Http/Controllers/TimesheetMissingController.php
app/Http/Filters/TimesheetFilter.php
app/Http/Filters/TimesheetMissingFilter.php
app/Models/Timesheet.php
app/Models/TimesheetMissing.php
app/Models/TimesheetMissingNote.php
app/Models/TimesheetNote.php
app/Policies/TimesheetPolicy.php
app/Providers/AuthServiceProvider.php
database/migrations/2023_10_26_142118_create_timesheet_note_tables.php
php-inis/xdebug.ini
routes/api.php

- New api timesheet/check-overlaps, check to see if the given date time range overlaps with any existing timesheet entries.
- Deprecated {timesheet,timesheet_missing}.{notes,reviewer_notes} and replaced with new tables timesheet_note, and timesheet_missing_note.
- Support creating a new timesheet at the same time a new timesheet missing request is created.

Timesheet administration work

---

app/Models/Slot.php

The check is done relative to the timezone the slot occurs in.

New slot attribute has_day_ended, set true if the slot is past the day it ends on.

---

app/Http/Controllers/ErrorLogController.php
app/Http/Controllers/RbsController.php
app/Jobs/RBSTransmitClubhouseMessageJob.php
app/Lib/RBS.php
app/Models/Person.php
app/Models/PersonMessage.php
app/Models/Position.php
app/Models/Role.php
app/Models/Slot.php
app/Models/TeamManager.php
app/Policies/BroadcastPolicy.php
database/migrations/2023_11_09_184006_megaphone_roles.php

- existing Megaphone permission considered year round now, and allows access to all broadcasts types, except the emergency broadcast feature. All positions are available to be messaged.
- New Megaphone Team On Playa permission: restricted access to the RBS, only allows messaging the positions the user is a Clubhouse Team Manager for.
- New Megaphone Emergency On Playa: access to the emergency broadcast.
- Broadcasts have an expiration associated, use to attach to a Clubhouse Message.
- Clubhouse Messages have an optional expiration date, only messages generated thru the RBS uses this.

RBS Team Support, new Megaphone permissions.

---

app/Http/Controllers/PersonScheduleController.php
app/Http/Filters/PersonFilter.php
app/Models/Person.php
app/Models/Schedule.php
app/Models/Slot.php
database/migrations/2023_11_11_140558_add_dependent_signup_to_slot.php

A parent/child slot relationship can be established so the signup counts work together. Primary target is the Troubleshooters where the TS Mentor (aka child slot) signups counts against the related TS shift (aka parent slot) signup counts.
e.g., if a TS Mentor shift has 2 signups, and the corresponding TS shift has 3 signups, then the TS shift will have an effective signup count of 5.

Parent/Child slot signup work.

---

app/Lib/PotentialClubhouseAccountFromSalesforce.php
app/Models/HandleReservation.php

- Allow a Salesforce record with the same callsign & bpguid as an existing Clubhouse account to be imported (really sync'ed). Deals with the situation where BM employees have an existing (auditor/non-ranger/etc) Clubhouse account yet want to become a Ranger as well.
- Swap over to the Handle Reservation table from the (now defunct) Reserved Callsign list.
- Report back the Handle Reservation record type, and expiration date, if the desired callsign is on the list.

Various Salesforce import enhancements

---

app/Http/Controllers/PersonFkaController.php
app/Http/Filters/PersonFilter.php
app/Lib/Intake.php
app/Lib/PersonSearch.php
app/Models/Person.php
app/Models/PersonFka.php
app/Models/PersonLanguage.php
app/Models/PersonMentor.php
app/Policies/PersonFkaPolicy.php
database/migrations/2024_03_30_103631_add_person_fka_table.php
routes/api.php
tests/Feature/PersonControllerTest.php

- Moved person.formerly_known_as into it's own table person_fka.
- New Person FKA controller.
- Better irrelevant FKAs (old auditor callsigns, bonked, or past prospective formatted) filtering on various reports.
- FKA searching improved thanks to metaphone searches (something not possible when the FKAs was one long string.)

Reworked FKA handling.

---

app/Http/Controllers/PersonController.php
app/Http/Controllers/TeamController.php
app/Lib/BulkTeamGrantRevoke.php
app/Lib/Membership.php
app/Models/Person.php
app/Models/PersonPosition.php
app/Models/PersonTeam.php
app/Models/Position.php
app/Models/PositionRole.php
app/Models/Team.php
app/Models/TeamRole.php
app/Policies/PersonPolicy.php
app/Policies/PositionPolicy.php
app/Policies/TeamPolicy.php
tests/Feature/PersonControllerTest.php
tests/Feature/PositionControllerTest.php

- Allow Admin & Tech Ninja permissions be associated with teams & positions.
- Only an Admin, regardless of the user being a team manager, can grant a team with the Admin permission associated.
- Only a Tech Ninja, regardless of the user being a team manager, can grant a team with the Tech Ninja permission associated.
- Allow teams and positions be editable by Admins. Tech Ninja may only adjust the associated permissions.

Loosened the restrictions on position and team management.

---

app/Models/Person.php

Handles the case where the mentors had a playa brain moment, and they really meant to pass the Alpha.

Add Dirt Shiny Penny when converting a bonked to active.

---

app/Lib/Reports/RadioEligibilityReport.php

The eligible hours was the highest hours out of the last 3 years instead of the most recent year worked within the last 3.

Fixed radio eligibility report to be inline with policy.

---

app/Http/Controllers/ProvisionController.php
app/Lib/BulkUploader.php
app/Lib/TicketAndProvisionsPackage.php
app/Models/Provision.php
tests/Feature/BulkUploadControllerTest.php

- Have Bulk Uploader verify the source and expiry years are actually years and not garbage.
- For the ticketing package, don't include the event radios.
- Explicit set the source and expiry year on all allocated provisions to the current year of upload.

Provision and ticketing work.

---

app/Http/Controllers/TimesheetController.php
app/Jobs/SignOutTimesheetsJob.php
app/Lib/Reports/OnDutyReport.php
app/Lib/Reports/OnDutyShiftLeadReport.php
app/Lib/Reports/PayrollReport.php
app/Models/Timesheet.php
app/Models/TimesheetMissing.php
app/Policies/TimesheetPolicy.php
routes/api.php

- Indicate when an entry exceeds 1.5x an associated shift sign up or 6 hours (i.e., 1.5*6 = 9 hours).
- Return the associated shift if any

Created On Duty Report instead of using Timesheet::findForQuery.

---

app/Http/Controllers/PersonPhotoController.php
app/Models/PersonPhoto.php

The VIPS library will hang when attempting to convert HEIC to JPG while running under AWS Fargate.
This does not occur when running under Docker (x86 & arm) or in the local development environment.

Disable HEIC support.

---

app/Lib/Reports/ShiftLeadReport.php

as Cane Toad observed, the report was previously pulling in data for all shifts, rather than just the selected one.
That was because these two blocks were ORing rather than ANDing, creating situations which were almost always true.
The root problem was a breaking change in Laravel: https://github.com/laravel/framework/issues/53184

fix date ranges for Shift Lead Report

---

app/Models/EventDate.php

Include before-event when trying to guess what period it is when no event date record exists. Used to help gate Timecard Year Round permission on the client side.

Event Date event period defaults work

---

app/Http/Controllers/PodController.php
app/Http/Controllers/SwagController.php
app/Http/Controllers/TimesheetController.php
app/Http/Filters/PersonFilter.php
app/Http/Filters/TimesheetFilter.php
app/Lib/Milestones.php
app/Models/Person.php
app/Models/Role.php
app/Models/Setting.php
app/Policies/PersonCertificationPolicy.php
app/Policies/PersonPolicy.php
app/Policies/PersonSwagPolicy.php
app/Policies/PodPolicy.php
app/Policies/PositionPolicy.php
app/Policies/RolePolicy.php
app/Policies/SwagPolicy.php
app/Policies/TimesheetPolicy.php
database/migrations/2025_02_17_110308_create_more_roles.php
database/schema/mysql-schema.dump
database/schema/mysql_testing-schema.dump
routes/api.php
tests/Feature/PersonControllerTest.php
tests/Feature/PositionSanityCheckControllerTest.php
tests/Feature/TimesheetControllerTest.php

- Renamed Timecard Year Round to Shift Management Self
- New permission Quartermaster: for QM reports, and swag access.
- New permission Shift Management: to control who can do shift check in/outs. Removed from Login Management.
- New permission Pod Management: to control access to the Cruise Direction Interface / Pod apis.

Restructured policies, introduced new permissions.

---

app/Models/ProspectiveApplication.php

The ProspectiveApplication::index method was slow because it screened handles for all records. This screening should only occur when retrieving individual records.

Only append the screened handles on individual record lookup.

---

app/Models/PersonEventInfo.php

- Removed a check for a now impossible null BMID being retrieved.
- Aid the frontend by indicating if the in-person training was passed. Previously it had to hunt it down in the list of all trainings.

Minor tweaks to PersonEventInfo.php

---

app/Exceptions/ScheduleSignUpException.php
app/Http/Controllers/PersonScheduleController.php
app/Models/Schedule.php
app/Models/Slot.php
tests/Feature/PersonScheduleControllerTest.php

- Improved the parent/child combined signup count calculations.
- Added shift "has ended" error reporting.
- Use an error string code instead of http status 404 for missing slot and missing signup reporting.
- Return the signup counts for the slot as well as other linked slots that might be affected. These values are included in successful operations, failed operations, and when the signup list is queried to keep the frontend in sync.

Fixed parent/child signup bugs. Improved signup error reporting.

---

app/Models/Slot.php

- Those were only used for slot management, and the ops/slots page was changed to do the lookup. Nowhere else is this used.

Don't eager-load parent_signup_slot or child_signup_slot.

---

resources/views/emails/daily-report.blade.php

it's pretty typical for photo uploading to be disabled for much of the year, and it's not really something that should concern the Tech Cadre.

stop daily report from barking when photo upload is disabled
